

coco_objects_priority = {
    "person": 10,
    "bicycle": 9,
    "car": 10,
    "motorcycle": 9,
    "airplane": 5,
    "bus": 10,
    "train": 10,
    "truck": 10,
    "boat": 5,
    "traffic light": 10,
    "fire hydrant": 7,
    "street sign": 8,
    "stop sign": 10,
    "parking meter": 3,
    "bench": 6,
    "bird": 2,
    "cat": 4,
    "dog": 4,
    "horse": 3,
    "sheep": 2,
    "cow": 2,
    "elephant": 2,
    "bear": 2,
    "zebra": 2,
    "giraffe": 2,
    "hat": 1,
    "backpack": 4,
    "umbrella": 6,
    "shoe": 1,
    "eye glasses": 1,
    "handbag": 4,
    "tie": 1,
    "suitcase": 5,
    "frisbee": 1,
    "skis": 1,
    "snowboard": 1,
    "sports ball": 1,
    "kite": 1,
    "baseball bat": 1,
    "baseball glove": 1,
    "skateboard": 2,
    "surfboard": 1,
    "tennis racket": 1,
    "bottle": 3,
    "plate": 2,
    "wine glass": 2,
    "cup": 3,
    "fork": 2,
    "knife": 3,
    "spoon": 2,
    "bowl": 2,
    "banana": 2,
    "apple": 2,
    "sandwich": 2,
    "orange": 2,
    "broccoli": 2,
    "carrot": 2,
    "hot dog": 2,
    "pizza": 2,
    "donut": 2,
    "cake": 2,
    "chair": 7,
    "couch": 6,
    "potted plant": 2,
    "bed": 6,
    "mirror": 2,
    "dining table": 5,
    "window": 8,
    "desk": 5,
    "toilet": 8,
    "door": 9,
    "tv": 1,
    "laptop": 3,
    "mouse": 2,
    "remote": 2,
    "keyboard": 2,
    "cell phone": 7,
    "microwave": 3,
    "oven": 4,
    "toaster": 3,
    "sink": 6,
    "refrigerator": 4,
    "blender": 3,
    "book": 3,
    "clock": 7,
    "vase": 2,
    "scissors": 3,
    "teddy bear": 1,
    "hair drier": 1,
    "toothbrush": 3,
    "hair brush": 3
}
